### ISSUE TITLE
workingCopy files aren't deleted on Windows

### ISSUE THREAD

**Issue by gayanper** [eclipse/lemminx-maven#37]
When working with the Language server some time huge number of files are created as below.

![image](https://user-images.githubusercontent.com/7471994/80608733-80629480-8a37-11ea-98d1-b6896cff1ab4.png)

**Comment by gayanper** [comment]
Seems this is **not an issue** in XML language server https://github.com/eclipse/lemminx/issues/668

**Comment by mickaelistria** [comment]
This was fixed a long time ago. Maybe try updating to latest m2e snapshot for the org.eclipse.m2e.editor.lemminx plugin.

**Comment by AObuchow** [comment]
Although I also thought this issue was fixed a while back, if it still exists, a temporary fix could be to change:
```Java
	workingCopy = File.createTempFile("workingCopy", '.' + file.getName(), file.getParentFile());
```
to
```Java
	workingCopy = File.createTempFile("workingCopy", '.' + file.getName());
```
So that the working copy file is created in the user's `/tmp/ ` directory, and won't appear in their workspace or git index.

**Comment by gayanper** [comment]
I'm running the m2e master. @mickaelistria do you mean to build a fresh copy out of lemminx-maven ?

**Comment by gayanper** [comment]
I tried a fresh build from of lemminx-maven with m2e master and the issue is not there it seems. I will put into testing and get back

**Comment by gayanper** [comment]
Well on windows i get this problem still. But I couldn’t reproduce it in linux. So i would say the issue is there where lot of file copies are created. But only visible in windows @AObuchow @mickaelistria

**Comment by AObuchow** [comment]
Thanks @gayanper for investigating further. If you figure out more information about when this issue occurs on windows (all of the time? some of the time? when a specific action is performed, etc) please report it. This will have to be fixed before the next release of Eclipse IDE.

**Comment by gayanper** [comment]
@AObuchow This happens always as soon as you invoke something that changes the file. Like content assist and type a char.

**Comment by gayanper** [comment]
@AObuchow is it normal to create this kind of working temp files? is it an intended behavior?

**Comment by AObuchow** [comment]
@gayanper Thanks for the additional info.

Yes, it's intended behavior, IIRC the working copy is created because the contents of the pom file might have changed before the file is saved, so we cache copies of it as changes are made. @mickaelistria  might be able to clarify.

**Comment by mickaelistria** [comment]
I think code at https://github.com/eclipse/lemminx-maven/blob/master/lemminx-maven/src/main/java/org/eclipse/lemminx/maven/MavenProjectCache.java#L173 could be refactored so that it doesn't generate a temp file, but instead reads the model from current document as inputStream and set the project.setFile(...) to the reference file.

@gayanper You can set system property `org.eclipse.wildwebdeveloper.xml.internal.XMLLanguageServer.debugPort` to the port of your choice and debug the Language Server as a remote Java application. However, it's not so comfortable; lemminx-maven has a decent test suite, you can instead build a unit test that reproduce the issue, and fix it; that's going to be more efficient.

**Comment by gayanper** [comment]
Looking at the code a little bit more, it seems like the file must get deleted after the project is resolved at line 195. The problem might be the file is held by the process so the delete operation actually failed. I noticed the last workingCopy file cannot be deleted until I close the pom editor. Which means the language server process is holding the file. Any comments on this finding @AObuchow  @mickaelistria ?

**Comment by mickaelistria** [comment]
That's also what we think so far. However, we didn't manage to find whether a stream or a process does also retain the file. Anyway, as mentioned in my previous comment, we can probably just perform the same tasks without creating a tmp file.

**Comment by gayanper** [comment]
@mickaelistria so your suggestion is to overwrite the pom.xml itself with the sent document bytes right ? I will try to reproduce this with a test case and try to fix and see how it goes.

**Comment by mickaelistria** [comment]
>
> @mickaelistria <https://github.com/mickaelistria> so your suggestion is
> to overwrite the pom.xml itself with the sent document bytes right ?
>

Not exactly.
My suggestion is to not overwrite any file, but to invoke
`mavenReader.read(new ByteArrayInputStream(document.getText().getBytes())`
instead. The workingCopy was useful in a previous version, and it got
copied here; but we actually don't need it, so let's drop it.
-- 
Mickael Istria
Eclipse IDE <https://www.eclipse.org/downloads/eclipse-packages/>
developer, for Red Hat Developers <https://developers.redhat.com/>

**Comment by gayanper** [comment]
@mickaelistria Does your Local and Remote repository tests fails in cli builds ?

**Comment by mickaelistria** [comment]
No, all tests pass from the IDE, with CLI locally or on CI.

-- 
Mickael Istria
Eclipse IDE <https://www.eclipse.org/downloads/eclipse-packages/>
developer, for Red Hat Developers <https://developers.redhat.com/>

**Comment by gayanper** [comment]
CLI Locally, I tried without the change as well. But still fails. Some timeout exceptions as well. In Eclipse when running the LocalPluginTests the testPluginConfigurationHover fails with a NPE.

**Comment by AObuchow** [comment]
> CLI Locally, I tried without the change as well. But still fails. Some timeout exceptions as well. In Eclipse when running the LocalPluginTests the testPluginConfigurationHover fails with a NPE.

Do you have the maven-plugin being referenced in testPluginConfigurationHover? In this case, maven-surefire-plugin version 2.22.2. If you don't have it locally in your .m2 folder, the test will probably fail

**Comment by gayanper** [comment]
> Do you have the maven-plugin being referenced in testPluginConfigurationHover? In this case, maven-surefire-plugin version 2.22.2. If you don't have it locally in your .m2 folder, the test will probably fail

Maybe, but isn't the unit tests should be neutral from the surrounding dependencies. Even if this considers this as an integration test (which I assume from its nature) should we setup the environment prior to running the integration tests ?

**Comment by gayanper** [comment]
It's working, my bad I altered my mirrors yesterday for testing the other issue.

**Comment by AObuchow** [comment]
> 
> Maybe, but isn't the unit tests should be neutral from the surrounding dependencies. Even if this considers this as an integration test (which I assume from its nature) should we setup the environment prior to running the integration tests ?

Yes but we aren’t there yet. I intend to add support for downloading a maven plugin if it’s referenced in the pom file & available in Maven central (or a remote repository) but not downloaded locally. IIRC the old m2e editor did this when trigger completion within a plugin tag.

**Comment by AObuchow** [comment]
@gayanper now that https://github.com/eclipse/lemminx-maven/commit/2f603ebdf693d01fe7e1fb9246dfe2e2204d2132 is merged, could you verify this fixes the bug on Windows when you have a moment? Thanks!

**Comment by AObuchow** [comment]
Thanks for the fix @gayanper !

**Comment by garretwilson** [comment]
I was directed here from [Eclipse Bug 563171](https://bugs.eclipse.org/bugs/show_bug.cgi?id=563171), but I'm unsure what this product is or why it is being tracked in GitHub rather than the main Eclipse Bugzilla (as ugly and as difficult to use as it is).

As can be seen in that bug, I just experienced this issue on Windows 10 using Eclipse Enterprise 2020-06 M2.

From the status of this bug it appears to have been fixed 10 days ago. Can someone confirm it will get into the Eclipse 2020-06 M3 release in a few days?

**Comment by AObuchow** [comment]
@garretwilson This project was [originally started on GitHub](https://github.com/AObuchow/lsp4xml-extensions-maven) and is not specific to m2e. It aims to provide m2e's features (and more) through the Language Server Protocol so that all LSP-client editors (VSCode, Eclipse, Emacs, etc.) can easily obtain maven pom editing support. This is part of the reason why it's on GitHub rather than Eclipse's Bugzilla instance.

> Can someone confirm it will get into the Eclipse 2020-06 M3 release in a few days?

Yes, the fix is already in the m2e snapshots which will be used for M3 :)

**Comment by garretwilson** [comment]
Thank you for the clarification and the confirmation, @AObuchow .

**Comment by AObuchow** [comment]
@garretwilson my pleasure!
If you find more bugs or annoyances with the pom editor after M3, please be sure to let us know by filing a bug ticket here (or seeing if one already exists).
